# Generated by Django 2.2.20 on 2021-05-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210505_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
